# Generated by Django 6.0.3 on 2026-03-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='apaar_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
