# Generated by Django 6.0.3 on 2026-03-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_student_apaar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbid',
            name='collateral_document',
            field=models.FileField(blank=True, null=True, upload_to='collateral/'),
        ),
    ]
