# Generated by Django 6.0.3 on 2026-03-08 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanbid_collateral_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField()),
                ('min_family_income', models.IntegerField()),
                ('max_loan_amount', models.IntegerField()),
                ('max_interest_rate', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.bank')),
            ],
        ),
    ]
