# Generated by Django 6.0.3 on 2026-03-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loancriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='potential_score',
            field=models.IntegerField(default=0),
        ),
    ]
