# Generated by Django 6.0.3 on 2026-06-19 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_tenure_years', models.PositiveIntegerField()),
                ('min_family_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_academic_score', models.PositiveIntegerField()),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('collateral_required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.bank')),
            ],
        ),
    ]
