# Generated by Django 6.0.3 on 2026-06-19 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loanproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_tenure_years', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('eligible', 'Eligible'), ('offer_generated', 'Offer Generated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.profile')),
                ('legacy_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.student')),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
