# Generated by Django 6.0.3 on 2026-06-19 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_applicationstatusevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible', models.BooleanField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loanapplication')),
                ('loan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanproduct')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
